name: Package tf module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Package module
      run: make
    - name: Check module
      run: make check
    - name: Release
      run: |
            npx\
              -p @semantic-release/changelog\
              -p @semantic-release/git\
              -p semantic-release\
              semantic-release\
              --repositoryUrl="https://github.com/${{github.repository}}.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}